baseURL: "https://gregorchristie.github.io"
languageCode: "en-us"
title: "Gregor Christie"
theme: "PaperMod"

menu:
    main:
        - name: Blog
          url: posts
          weight: 5
        - name: Portfolio
          url: portfolio
          weight: 10
        - name: About
          url: about
          weight: 15

params:
  homeInfoParams:
    Title: Gregor Christie 222222
    Content: >
      Software Engineering Student

      - C, Java, Python, Haskell

  socialIcons:
    - name: "github"
      url: "https://github.com/GregorChristie"
    - name: "twitter"
      url: "https://twitter.com/GregorChristie_"