baseURL: "https://gregorchristie.github.io"
languageCode: "en-us"
title: "Gregor Christie"
theme: "PaperMod"

menu:
    main:
        - name: Blog
          url: posts
          weight: 5
        - name: Portfolio
          url: about
          weight: 5

params:
  homeInfoParams:
    Title: Gregor Christie
    Content: >
      Software Engineering Student

      - C, Java, Python, Haskell

  socialIcons:
    - name: "github"
      url: "https://github.com/GregorChristie"
    - name: "twitter"
      url: "https://twitter.com/GregorChristie_"